# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
# pre-commit hook itself
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-merge-conflict
    -   id: mixed-line-ending
    -   id: name-tests-test
        language: python
        types: [ python ]
        args: ['--pytest-test-first']
        exclude: ^.*/fixtures/.*
# pre-commit hook for mypy
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
    -   id: mypy
        additional_dependencies: [
            "SQLAlchemy==2.0.31",
        ]
        exclude: ^tests/
# pre-commit hook for ruff
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.5.5
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
