name: CI PULL REQUEST - Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-validation:
    name: Code Validation
    secrets: inherit
    uses: './.github/workflows/ci_code_validation.yml'
